### ISSUE TITLE
KeyError: 'conflict_entailment'

### ISSUE THREAD

**Issue by Danielznn16** [OSU-NLP-Group/LLM-Knowledge-Conflict#1]
Hi during the reproduction of the paper, we encountered error of

```bash
user@conda-base:~/LLM-Knowledge-Conflict/code$ python3 ./run.py --input_file ../conflictQA/conflictQA-strategyQA-chatgpt.json --output_file ../out/conflictQA-strategy-chatgpt.json

Traceback (most recent call last):
  File "/data/user_use/LLM-Knowledge-Conflict/code/./run.py", line 18, in <module>
    test_data = build_zeroshot_prompt_strategyQA_with_singleSource_evidence(args.input_file, mode="explicit", evidence_order='random')
  File "/data/user_use/LLM-Knowledge-Conflict/code/prompt_preparation.py", line 244, in build_zeroshot_prompt_strategyQA_with_singleSource_evidence
    if unit['conflict_entailment'] != True:
KeyError: 'conflict_entailment'
```
We wonder is there anything we were missing or we did wrong with.

Thank you : )

**Comment by hsaest** [comment]
Apologies for the delay in my response. I hope this isn't too late. 

The term 'conflict_entailment' pertains to the flag used to determine whether the 'counter_memory' supports the 'counter_answer'. For this process, we utilize the deberta-v2-xxlarge model to achieve our results. Similarly, 'parametric_entailment' is employed to evaluate if the 'parametric_memory' corroborates the 'parametric_answer'.

It's an extra and easy process, so we do not provide the code.  You can see our data format in the provided examples in data/example_data.json.
