### ISSUE TITLE
How to get 'memory_answer' and 'parametric_memory'?

### ISSUE THREAD

**Issue by BUGLI27** [OSU-NLP-Group/LLM-Knowledge-Conflict#2]
Hello, great job, pls how do I get `memory_answer` and `parametric_memory` automatically, did you do any post-processing work to extract these informations?
I've found that the model doesn't answer in the format I'm supposed to.
For example, when I prompt **Qwen-7b** `The first paragraph answers the question and the second paragraph gives the reason.\n\nQ:What is George Rankin's occupation?\nA:`
The answer is `George Rankin does not have specific information provided in your statement to determine his occupation. Without further context or details, we cannot directly say what his profession is based on the given information. If you can provide additional context or clarify the reference, I'd be happy to help identify his occupation.`
How can I extract the `memory_answer` and `parametric_memory`?

**Comment by hsaest** [comment]
Hi,

Thank you for your interest in our work. It seems Qwen-7B refuses to provide an answer to this question, which also exists in our experiments. For these cases, we discard them. 

If the model follows instructions well, you can extract the memory_answer and parametric_memory from paragraphs 1 and 2, respectively. We suggest that you polish the prompts. 

Our prompt for Qwen-7B is:
In the first paragraph, you are expected to answer the question. The answer should be as short as possible, but should be a complete sentence. In the second paragraph, you should provide the evidence. The evidence should be as extensive as possible to support the answer. Do not generate a new question. The generated content should follow the format "Answer: \nEvidence: "\n\nQuestion:{Question}\n"

I hope this can help you. If you have any further questions, feel free to contact us.

Best,
Jian

**Comment by BUGLI27** [comment]
Thanks, it helps a lot. So that's the reason why the data size is different for different files (Models refuses to provide an answer sometimes, so discard them)?

**Comment by hsaest** [comment]
True, that's one of the reasons for the difference in size. Actually, the quality of elicited parametric memory / generated counter-memory and the double check of parametric memory (please refer to our paper for these) all bring data loss. We discard low-quality data to guarantee the reliability of our conclusions.
